### PR TITLE
fix(cmd): add network validation in coffee cmd inputs

### LINKED ISSUE #270: Network Validation in Command Line Inputs
## Description 
Currently, `coffee` does not validate if the network supplied in the command line is valid.
Running `coffee -n remote list` by mistake creates `/Users/tareknasser/.coffee/remote`

### PR DESCRIPTION
**Pull request by Anyitechs**
This PR validates the argument passed into the `-n` flag, and ensures only supported CLN networks are created in the `/Users/User/.coffee` directory, and closes #270 .

### Implementation
The current implementation consists of:

- An enum (`ClnNetwork`) with `Mainnet`, `Testnet`, `Signet`, and `Regtest` as variants
- A `ClnNetwork` implementation (`impl`) with a `from_str` function that `match`es on the `network` (`&str`) argument and returns a `ClnNetwork` variant, and  `to_str` function that `match`es on the `ClnNetwork` variant and returns the network `String`.
- The `network` function validates the `-n` argument.

### Current Behaviour
The validation works as expected, so passing in a random name as the network name will not create the directory but the command returns the same output as below regardless of the network name. Also, passing in a random network name and running `coffee -n remote list` for the first time ignores the invalid network name and creates a `/Users/ifeanyichukwu/.coffee/bitcoin` directory for example, but running the command again doesn't create a `../.coffee/bitcoin` directory again.

```
ifeanyichukwu@IfeanyiukwusMBP coffee % coffee -n remote list
● Plugins installed
╭───────────────────────────────────────────╮
│ ●   Language   Name   Enabled   Exec path 
├───────────────────────────────────────────┤
╰───────────────────────────────────────────╯
```

### How to test

- cd into the `coffee` directory
- Run `make install`
- Run `coffee -n remote list`

### CODE REVIEW

File: coffee_cmd/src/cmd.rs [hunk 1]
```diff
@@ -1,5 +1,6 @@
 //! Coffee command line arguments definition.
 use clap::{Parser, Subcommand};
+use coffee_lib::{error, errors::CoffeeError};
```
Comment (vincenzopalazzo) [inline coffee_cmd/src/cmd.rs:3]:
```suggestion
use coffee_lib::error;
use coffee_lib::errors::CoffeeError;
```

File: coffee_cmd/src/cmd.rs [hunk 2]
```diff
@@ -133,6 +134,36 @@ impl From<&RemoteAction> for coffee_core::RemoteAction {
...
+
+impl ClnNetwork {
+    fn from_str(network: &str) -> Option<Self> {
+        
+        match network {
+            "mainnet" => Some(Self::Mainnet),
+            "testnet" => Some(Self::Testnet),
+            "signet" => Some(Self::Signet),
+            "regtest" => Some(Self::Regtest),
+            _ => None,
```
Comment (vincenzopalazzo) [inline coffee_cmd/src/cmd.rs:153]: What about Liquid?

File: coffee_cmd/src/cmd.rs [hunk 3]
```diff
@@ -133,6 +134,36 @@ impl From<&RemoteAction> for coffee_core::RemoteAction {
...
+    }
+
+    fn to_str(network: Self) -> Option<String> {
+        match network {
+            Self::Mainnet => Some("mainnet".to_string()),
+            Self::Testnet => Some("testnet".to_string()),
+            Self::Signet => Some("signet".to_string()),
+            Self::Regtest => Some("regtest".to_string()),
+        }
+    }
```
Comment (vincenzopalazzo) [inline coffee_cmd/src/cmd.rs:164]: implement the `std::fmt::Display` trait not use this an hack

File: coffee_cmd/src/cmd.rs (hunk 2 above)
Comment (vincenzopalazzo) [inline coffee_cmd/src/cmd.rs:153]: implement the `From<&str>` trait, do not reivent rust

File: coffee_cmd/src/cmd.rs [hunk 4]
```diff
@@ -147,7 +178,10 @@ impl coffee_core::CoffeeArgs for CoffeeArgs {
     }
 
     fn network(&self) -> Option<String> {
-        self.network.clone()
+        let network = self.network.clone().ok_or_else(|| error!("Network is not set")).ok()?;
+        let validated_network = ClnNetwork::from_str(&network.to_lowercase()).ok_or_else(|| error!("Invalid network name")).ok()?;
```
Comment (vincenzopalazzo) [inline coffee_cmd/src/cmd.rs:182]: I think you do not run `make` command, this code looks like unformatted.

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]

**Comment by Anyitechs** [comment]
Thank you for the review. I'll work on these and update the PR.

File: coffee_cmd/src/cmd.rs [hunk 5]
```diff
@@ -133,6 +136,43 @@ impl From<&RemoteAction> for coffee_core::RemoteAction {
...
+impl Display for ClnNetwork {
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        let s = match self {
+            ClnNetwork::Mainnet => "mainnet",
+            ClnNetwork::Testnet => "testnet",
+            ClnNetwork::Signet => "signet",
+            ClnNetwork::Regtest => "regtest",
+            ClnNetwork::Liquid => "liquid",
+        };
+        write!(f, "{}", s)
```
Comment (vincenzopalazzo) [inline coffee_cmd/src/cmd.rs:157]:
```suggestion
        write!(f, "{s}")
```

File: coffee_cmd/src/cmd.rs [hunk 6]
```diff
@@ -133,6 +136,43 @@ impl From<&RemoteAction> for coffee_core::RemoteAction {
...
+    type Error = String;
+
+    fn try_from(network: String) -> Result<Self, Self::Error> {
+        match network.as_str() {
+            "mainnet" => Ok(Self::Mainnet),
+            "testnet" => Ok(Self::Testnet),
+            "signet" => Ok(Self::Signet),
+            "regtest" => Ok(Self::Regtest),
+            "liquid" => Ok(Self::Liquid),
+            _ => Err(format!("{} is not a valid network name", network)),
```
Comment (vincenzopalazzo) [inline coffee_cmd/src/cmd.rs:171]:
```suggestion
            _ => Err(format!("{network} is not a valid network name")),
```

File: coffee_cmd/src/cmd.rs [hunk 7]
```diff
@@ -147,7 +187,17 @@ impl coffee_core::CoffeeArgs for CoffeeArgs {
     }
 
     fn network(&self) -> Option<String> {
-        self.network.clone()
+        let network = self
+            .network
+            .clone()
+            .ok_or_else(|| error!("Network is not set"))
```
Comment (vincenzopalazzo) [inline coffee_cmd/src/cmd.rs:193]:
```suggestion
            .ok_or_else(|| error!("Network is not defined"))
```

File: coffee_cmd/src/cmd.rs [hunk 8]
```diff
@@ -147,7 +187,17 @@ impl coffee_core::CoffeeArgs for CoffeeArgs {
...
+            .ok()?;
+        let validated_network = ClnNetwork::try_from(network.to_lowercase()).ok();
+
+        match validated_network {
+            Some(valid_network) => format!("{}", valid_network).into(),
```
Comment (vincenzopalazzo) [inline coffee_cmd/src/cmd.rs:198]:
```suggestion
            Some(valid_network) => format!("{valid_network}").into(),
```

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
Good code, some small minor changes

**Comment by Anyitechs** [comment]
> Good code, some small minor changes

Thank you for the review. I've addressed all the requested changes and updated the PR.

Let me know if there's anything I'm missing.

File: coffee_cmd/src/cmd.rs [hunk 9]
```diff
@@ -1,5 +1,8 @@
 //! Coffee command line arguments definition.
 use clap::{Parser, Subcommand};
+use coffee_lib::error;
+use coffee_lib::errors::CoffeeError;
+use std::fmt::Display;
```
Comment (vincenzopalazzo) [inline coffee_cmd/src/cmd.rs:5]: look at how we organize the import, we follow the following rules

```
std import

external dependencies import

coffee importa

crate import
```

But this can be addressed in a followup PR

**Review by vincenzopalazzo — APPROVED** [review]
ACK ddaa0dc1a51021d5fe37effe301f944c49c58049

File: coffee_cmd/src/cmd.rs (hunk 9 above)
Comment (Anyitechs) [reply coffee_cmd/src/cmd.rs:5]: Thank you for pointing that out. I'll address that asap!

Comment (Anyitechs) [reply coffee_cmd/src/cmd.rs:5]: I've addressed this in #276.
