### PR TITLE
fix warnings that cargo clippy outputs

### LINKED ISSUE #109: fix cargo clippy
I never test the code with ` cargo clippy --all --tests`

We should fix the warnings :)

### PR DESCRIPTION
**Pull request by tareknaser360**
fixes #109

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]

File: coffee_plugin/src/plugin.rs [hunk 1]
```diff
@@ -1,5 +1,5 @@
-pub mod plugin;
+pub mod plugin_mod;
 mod state;
 
-pub use plugin::*;
+pub use plugin_mod::*;
```
Comment (vincenzopalazzo) [inline coffee_plugin/src/plugin.rs:4]: I do not like this, I preferer on top of this the `#[allow(....)]`
